"""
Standalone script to regenerate Sankey diagram from saved flow metrics.

This script reads the flow_metrics.json file (generated by qc_add_metadata.py)
and regenerates the Sankey diagram without re-running the entire QC pipeline.

Usage:
    python plot_study_sankey.py [--flow-metrics PATH] [--output-dir PATH]
"""

import argparse
import json
import os
import sys

# Import the generate_sankey_diagram function from qc_add_metadata
from bac_metadata.pp.qc_add_metadata import generate_sankey_diagram, OUTPUT_DIR


def load_flow_metrics(flow_metrics_path: str) -> dict:
    """
    Load flow metrics from JSON file.
    
    Parameters:
    -----------
    flow_metrics_path : str
        Path to flow_metrics.json file
    
    Returns:
    --------
    dict
        Flow metrics dictionary
    """
    if not os.path.exists(flow_metrics_path):
        raise FileNotFoundError(f"Flow metrics file not found: {flow_metrics_path}")
    
    with open(flow_metrics_path, 'r', encoding='utf-8') as f:
        flow_metrics = json.load(f)
    
    return flow_metrics


def main():
    """Main function to regenerate Sankey diagram."""
    parser = argparse.ArgumentParser(
        description='Regenerate Sankey diagram from saved flow metrics'
    )
    
    parser.add_argument(
        '--flow-metrics',
        type=str,
        default=None,
        help='Path to flow_metrics.json file. If not provided, uses default path in output_dir.'
    )
    parser.add_argument(
        '--output-dir',
        type=str,
        default=OUTPUT_DIR,
        help=f'Directory to write output files (default: {OUTPUT_DIR})'
    )
    
    args = parser.parse_args()
    
    # Determine flow_metrics path
    if args.flow_metrics is None:
        flow_metrics_path = os.path.join(args.output_dir, 'flow_metrics.json')
    else:
        flow_metrics_path = args.flow_metrics
    
    print("="*80)
    print("REGENERATING SANKEY DIAGRAM FROM SAVED FLOW METRICS")
    print("="*80)
    print(f"Flow metrics file: {flow_metrics_path}")
    print(f"Output directory: {args.output_dir}")
    print()
    
    try:
        # Load flow metrics
        print("Loading flow metrics...")
        flow_metrics = load_flow_metrics(flow_metrics_path)
        print("✓ Flow metrics loaded successfully")
        print()
        
        # Display summary
        print("Flow metrics summary:")
        print(f"  Total input: {flow_metrics['inputs'].get('total', 0):,} samples")
        print(f"  Bakrep: {flow_metrics['inputs'].get('bakrep', 0):,}")
        print(f"  Refseq: {flow_metrics['inputs'].get('refseq', 0):,}")
        print(f"  NCTC: {flow_metrics['inputs'].get('nctc', 0):,}")
        print(f"  Removed studies: {flow_metrics['removed'].get('count', 0):,}")
        print(f"  KPSC: {flow_metrics['klebsiella'].get('kpsc', 0):,}")
        print(f"  Non-KPSC: {flow_metrics['klebsiella'].get('non_kpsc', 0):,}")
        print(f"  Final KPSC set: {flow_metrics['final'].get('kpsc_final_set', 0):,}")
        print()
        
        # Generate Sankey diagram
        print("Generating Sankey diagram...")
        generate_sankey_diagram(flow_metrics, args.output_dir)
        print()
        print("="*80)
        print("SANKEY DIAGRAM REGENERATION COMPLETE")
        print("="*80)
        
    except FileNotFoundError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        print("\nPlease run qc_add_metadata.py first to generate flow_metrics.json", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"ERROR: {type(e).__name__}: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
